//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octoller.ASUF.Kernel.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultPath {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultPath() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Octoller.ASUF.Kernel.Resource.DefaultPath", typeof(DefaultPath).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Download.
        /// </summary>
        internal static string defoltRootFolder {
            get {
                return ResourceManager.GetString("defoltRootFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Temp.
        /// </summary>
        internal static string defoltTempFolder {
            get {
                return ResourceManager.GetString("defoltTempFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Sorted\Documents\.
        /// </summary>
        internal static string docFolder {
            get {
                return ResourceManager.GetString("docFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Sorted\Gif\.
        /// </summary>
        internal static string gifFolder {
            get {
                return ResourceManager.GetString("gifFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Sorted\Image\.
        /// </summary>
        internal static string imageFolder {
            get {
                return ResourceManager.GetString("imageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Sorted\Other\.
        /// </summary>
        internal static string otherFolder {
            get {
                return ResourceManager.GetString("otherFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Settings.json.
        /// </summary>
        internal static string settingFileName {
            get {
                return ResourceManager.GetString("settingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Settings\.
        /// </summary>
        internal static string settingFolderName {
            get {
                return ResourceManager.GetString("settingFolderName", resourceCulture);
            }
        }
    }
}
